### ISSUE TITLE
can not download pretrained model

### ISSUE THREAD

**Issue by gjylt** [zjhuang22/maskscoring_rcnn#13]
**While I excute the code:**

python tools/train_net.py --config-file "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

**A error returned:**

2019-03-11 14:57:30,345 maskrcnn_benchmark.utils.checkpoint INFO: Loading checkpoint from catalog://ImageNetPretrained/MSRA/R-50
2019-03-11 14:57:30,345 maskrcnn_benchmark.utils.checkpoint INFO: catalog://ImageNetPretrained/MSRA/R-50 points to https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
Downloading: "https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl" to pretrained_models/R-50.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 53, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 128, in _load_file
    cached_f = cache_url(f, model_dir=self.cfg.MODEL.PRETRAINED_MODELS)
  File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/model_zoo.py", line 54, in cache_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 88, in _download_url_to_file
    u = urlopen(url)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**how could I get the pretrained model by other way.**

**Comment by zjhuang22** [comment]
> **While I excute the code:**
> 
> python tools/train_net.py --config-file "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1
> 
> **A error returned:**
> 
> 2019-03-11 14:57:30,345 maskrcnn_benchmark.utils.checkpoint INFO: Loading checkpoint from catalog://ImageNetPretrained/MSRA/R-50
> 2019-03-11 14:57:30,345 maskrcnn_benchmark.utils.checkpoint INFO: catalog://ImageNetPretrained/MSRA/R-50 points to https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
> Downloading: "https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl" to pretrained_models/R-50.pkl
> Traceback (most recent call last):
> File "tools/train_net.py", line 171, in 
> main()
> File "tools/train_net.py", line 164, in main
> model = train(cfg, args.local_rank, args.distributed)
> File "tools/train_net.py", line 53, in train
> extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
> File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load checkpoint = self._load_file(f) File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 128, in _load_file
> cached_f = cache_url(f, model_dir=self.cfg.MODEL.PRETRAINED_MODELS)
> File "/media/**/ffd15abb-ef51-4903-a331-ef8327a5864a/DukTo/svn/object-detection/maskscoring_rcnn/maskrcnn_benchmark/utils/model_zoo.py", line 54, in cache_url _download_url_to_file(url, cached_file, hash_prefix, progress=progress) File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 88, in _download_url_to_file
> u = urlopen(url)
> File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 223, in urlopen return opener.open(url, data, timeout) File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 532, in open
> response = meth(req, response)
> File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 642, in http_response 'http', request, response, code, msg, hdrs) File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 570, in error
> return self._call_chain(*args)
> File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 504, in _call_chain result = func(*args) File "/home/**/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/urllib/request.py", line 650, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> **how could I get the pretrained model by other way.**

I have updated pretrained models in README.md

**Comment by maomaochongchh** [comment]
@zjhuang22 @gjylt Hello, did you get the same results with the paper by running test_net.py? I download the .pkl file and use it to test, but I got clearly wrong results.
`
2019-03-21 17:19:01,079 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 9.300105363128172e-09), ('AP50', 6.022500060225e-08), ('AP75', 0.0), ('APs', 9.522348740812624e-09), ('APm', 0.0), ('APl', 0.0)])), ('segm', OrderedDict([('AP', 1.4857428119762759e-08), ('AP50', 5.942971247905103e-08), ('AP75', 0.0), ('APs', 1.519675543192826e-08), ('APm', 0.0), ('APl', 0.0)]))])

`

**Comment by YubinXie** [comment]
@maomaochongchh  The pre-trained file the author provides is likely not trained by author... It could be pre-train file for the author, which is from imageNet detection task and not for segmentation...
