### ISSUE TITLE
DataLoader worker (pid 2753) exited unexpectedly with exit code 127??

### ISSUE THREAD

**Issue by TyroneLi** [zjhuang22/maskscoring_rcnn#15]
2019-03-12 15:03:22,550 maskrcnn_benchmark.trainer INFO: Start training
python: symbol lookup error: /home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
python: symbol lookup error: /home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
python: symbol lookup error: /home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
python: symbol lookup error: /home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/home/king/githubToolkit/maskscoring_rcnn/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/king/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2753) exited unexpectedly with exit code 127. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

Why this occur??Is that because my GPU memory or system shared memory limited??or ln command maked some potential mistakes?someone met this problem?

**Comment by TyroneLi** [comment]
I solved this problem through replacing python3.6.0 by python3.6.5

**Comment by Iamal1** [comment]
Thank you so much, I met the same problem and solved it as you suggested
