### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhuliqian** [zjhuang22/maskscoring_rcnn#19]
2019-03-15 20:43:52,007 maskrcnn_benchmark.utils.checkpoint INFO: Loading checkpoint from catalog://ImageNetPretrained/MSRA/R-50
2019-03-15 20:43:52,007 maskrcnn_benchmark.utils.checkpoint INFO: catalog://ImageNetPretrained/MSRA/R-50 points to https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
2019-03-15 20:43:52,008 maskrcnn_benchmark.utils.checkpoint INFO: url https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl cached in pretrained_models/R-50.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 53, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/chase/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/home/chase/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 133, in _load_file
    return load_c2_format(self.cfg, f)
  File "/home/chase/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 155, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "/home/chase/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 146, in load_resnet_c2_format
    state_dict = _load_c2_pickled_weights(f)
  File "/home/chase/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 124, in _load_c2_pickled_weights
    data = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by zhuliqian** [comment]
catalog://ImageNetPretrained/MSRA/R-50,this can be download?

**Comment by celabi** [comment]
You can download R50.pkl into the pretrained file

**Comment by lapetite123** [comment]
can you tell me where to download the pretrained model, I tried to download from https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl, but it shows 'ERROR 404: Not Found'.
