### ISSUE TITLE
error when use multi_gpus 

### ISSUE THREAD

**Issue by maomaochongchh** [zjhuang22/maskscoring_rcnn#23]
When I use your script to run it with multi-gpus, error happened:
`
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 140, in main
    backend="nccl", init_method="env://"
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 101, in init_process_group
    group_name, rank)
RuntimeError: Address already in use at /opt/conda/conda-bld/pytorch-nightly_1552799380021/work/torch/lib/THD/process_group/General.cpp:20
Traceback (most recent call last):
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/distributed/launch.py", line 238, in <module>
    main()
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/distributed/launch.py", line 234, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/chh/anaconda2/envs/maskrcnn_benchmark/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/e2e_ms_rcnn_R_50_FPN_1x.yaml']' returned non-zero exit status 1.
`

**Comment by celabi** [comment]
I had the same problem. So I tried to use a stable pytorch instead of pytorch-nightly ,it works.

**Comment by maomaochongchh** [comment]
Thank you! I solved that error. The script I use is below:
`
NGPUS=4
GPU_ID=0,1,2,3
CUDA_VISIBLE_DEVICES=${GPU_ID} python -m torch.distributed.launch --nproc_per_node=$NGPUS --master_addr 127.0.0.2 --master_port 29501 tools/train_net.py --config-file "maskscoring_rcnn/configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1
`
And add a line in train_net.py, "os.environ['WORLD_SIZE'] = '4'"

**Comment by Real-YeJ** [comment]
> Thank you! I solved that error. The script I use is below:
> `NGPUS=4 GPU_ID=0,1,2,3 CUDA_VISIBLE_DEVICES=${GPU_ID} python -m torch.distributed.launch --nproc_per_node=$NGPUS --master_addr 127.0.0.2 --master_port 29501 tools/train_net.py --config-file "maskscoring_rcnn/configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1`
> And add a line in train_net.py, "os.environ['WORLD_SIZE'] = '4'"

I had the same proplem. I try your method,but it doesn't work. Can you tell me the root cause of the problem?
