### ISSUE TITLE
runtimeerror :invalid arugment 0

### ISSUE THREAD

**Issue by celabi** [zjhuang22/maskscoring_rcnn#25]
My gpus are RTX2080 
os = ubuntu 16.04.6
cuda version = 9.0.176
python = 3.6
pytorch = 1.0.1

when I use script " export NGPUS=8
  python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 700"

Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 167, in main
    test(cfg, model, args.distributed)
  File "tools/train_net.py", line 104, in test
    maskiou_on=cfg.MODEL.MASKIOU_ON
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 379, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 31, in compute_on_dataset
    output = model(images)
  File "/home/d/.conda/envs/ms/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/d/.conda/envs/ms/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 43, in forward
    loss_maskiou, detections = self.maskiou(roi_feature, detections, selected_mask, labels, maskiou_targets)
  File "/home/d/.conda/envs/ms/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py", line 41, in forward
    x = self.feature_extractor(features, selected_mask)
  File "/home/d/.conda/envs/ms/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/github/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py", line 39, in forward
    x = torch.cat((x, mask_pool), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 47 and 250 in dimension 0 at /opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/THC/generic/THCTensorMath.cu:83

**Comment by tkianai** [comment]
`TEST.IMS_PER_BTACH=1` works fine.
