### ISSUE TITLE
how to add other dataset?

### ISSUE THREAD

**Issue by 13012476909** [zjhuang22/maskscoring_rcnn#30]
Hi, I want to train on diffierent dataset, so what should I modify?
Looking forward to your reply.

**Comment by zjhuang22** [comment]
Hi, you can refer to https://github.com/facebookresearch/maskrcnn-benchmark/issues/15 for more details.

**Comment by 13012476909** [comment]
Thanks you very much!

**Comment by DetectionIIT** [comment]
修改paths_catalog.py和类别数量后，运行：
dataset_name coco_2014_train
loading annotations into memory...
Done (t=4.41s)
creating index...
index created!
dataset_name coco_2014_trainval
loading annotations into memory...
Done (t=5.22s)
creating index...
index created!
dataset_name coco_2014_val
loading annotations into memory...
Done (t=0.55s)
creating index...
index created!
datasets [<maskrcnn_benchmark.data.datasets.concat_dataset.ConcatDataset object at 0x7fb07c085fd0>]
dataset <maskrcnn_benchmark.data.datasets.concat_dataset.ConcatDataset object at 0x7fb07c085fd0>
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/disk2/gg/msrcnn/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 157, in make_data_loader
    sampler = make_data_sampler(dataset, shuffle, is_distributed)
  File "/home/disk2/gg/msrcnn/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 62, in make_data_sampler
    sampler = torch.utils.data.sampler.RandomSampler(dataset)
  File "/home/disk2/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0


请问您在训练自己数据的时候还改了什么么？给的链接挺麻烦的？
