### ISSUE TITLE
How can I make use of multiple GPUs on a single server?

### ISSUE THREAD

**Issue by Le0000000000n** [zjhuang22/maskscoring_rcnn#35]
I tried changing WORLD_SIZE and CUDA_VISIBLE_DEVICES environment variables, but I got errors when init process group:

os.environ['WORLD_SIZE'] = '2'  
os.environ["CUDA_VISIBLE_DEVICES"] = "1,9"

num_gpus = int(os.environ["WORLD_SIZE"]) if "WORLD_SIZE" in os.environ else 1
args.distributed = num_gpus > 1

Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/maskscoring_RCNN/train_net.py", line 178, in <module>
    main()
  File "/opt/maskscoring_RCNN/train_net.py", line 145, in main
    backend="nccl", init_method="env://"
  File "/root/anaconda3/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 101, in init_process_group
    group_name, rank)
RuntimeError: rank is not set but it is required for env:// init method at /opt/conda/conda-bld/pytorch_1549628766161/work/torch/lib/THD/process_group/General.cpp:20

**Comment by zjhuang22** [comment]
Trying running this scripts CUDA_VISIBLE_DEVICES=1,9 python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml"

**Comment by Le0000000000n** [comment]
> Trying running this scripts CUDA_VISIBLE_DEVICES=1,9 python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml"

Thank you!
I succeed with:

python3 -u -m torch.distributed.launch --nproc_per_node 2 train_net.py --config-file configs/e2e_ms_rcnn_R_50_FPN_1x.yaml SOLVER.IMS_PER_BATCH 8 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1
