### ISSUE TITLE
I encountered some problems during test

### ISSUE THREAD

**Issue by WY51BE** [zjhuang22/maskscoring_rcnn#41]
(maskrcnn) wuyi@nclab:~/github/maskscoring_rcnn/tools$ python test_net.py
Traceback (most recent call last):
  File "test_net.py", line 12, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/media/dat1/users/master/2019/wuyi/github/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 20, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/media/dat1/users/master/2019/wuyi/github/maskscoring_rcnn/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/media/dat1/users/master/2019/wuyi/github/maskscoring_rcnn/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/media/dat1/users/master/2019/wuyi/github/maskscoring_rcnn/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /media/dat1/users/master/2019/wuyi/github/maskscoring_rcnn/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z20ROIPool_forward_cudaRKN2at6TensorES2_fii

I'm confused，you can help me with it?

**Comment by zjhuang22** [comment]
Have you install maskrcnn_benchmark "python setup.py build develop"

**Comment by WY51BE** [comment]
Yes，i have done that.
![image](https://user-images.githubusercontent.com/26472153/56805630-46771500-685c-11e9-891c-bda80ad6c1dc.png)
I also read the Troubleshooting.md from maskrcnn-benchmark.
My nvcc is “Cuda compilation tools, release 7.5, V7.5.17”,but my cuda is 8.0,Could it be caused by this?I don't have root access，I don't know how to modify nvcc.

**Comment by zjhuang22** [comment]
I think the problem may be cuda 8.0. You can install cuda 9.0 locally and add to the env.

**Comment by lingbo666** [comment]
@WY51BE hello, I am also confused about this problem, have you solved it? thanks in advance.
