### ISSUE TITLE
train problem for AttributeError: 'list' object has no attribute 'resize'

### ISSUE THREAD

**Issue by sisivol** [zjhuang22/maskscoring_rcnn#42]
loading annotations into memory...
Done (t=14.28s)
creating index...
index created!
loading annotations into memory...
Done (t=1.97s)
creating index...
index created!
2019-05-06 18:22:29,797 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/cs/github/maskscoring_rcnn/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/cs/github/maskscoring_rcnn/maskrcnn_benchmark/data/datasets/coco.py", line 36, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/home/lj/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torchvision-0.2.3a0+7a4845a-py3.7.egg/torchvision/datasets/coco.py", line 114, in __getitem__
    img, target = self.transforms(img, target)
  File "/cs/github/maskscoring_rcnn/maskrcnn_benchmark/data/transforms/transforms.py", line 15, in __call__
    image, target = t(image, target)
  File "/cs/github/maskscoring_rcnn/maskrcnn_benchmark/data/transforms/transforms.py", line 58, in __call__
    target = target.resize(image.size)
AttributeError: 'list' object has no attribute 'resize'

(with coco2017  dataset )
can anyone tell me how to fix it?thanks!!

**Comment by HAILUWANG** [comment]
I have the same problem.Do you solve it?Thank you

**Comment by sisivol** [comment]
No. You can open a new issue abou it.

HAILUWANG <notifications@github.com> 于2019年5月7日周二 下午3:49写道：

**Comment by tjzjp** [comment]
> I have the same problem.Do you solve it?Thank you

have you fixed it? I met the same problem, thank you

**Comment by npurson** [comment]
Try to use torchvision==0.2.1
