### ISSUE TITLE
AP (mask) is 35.4

### ISSUE THREAD

**Issue by yhcao6** [zjhuang22/maskscoring_rcnn#46]
```
Loading and preparing results...
DONE (t=3.93s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=44.62s).
Accumulating evaluation results...
DONE (t=5.38s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.354
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.558
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.380
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.161
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.379
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.517
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.298
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.450
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.468
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.269
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.505
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.619
2019-05-09 06:57:34,621 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.3759153459368749)
, ('AP50', 0.5908149513831737), ('AP75', 0.407623512259985), ('APs', 0.21592651568910282), ('APm', 0.40564621888303226),
 ('APl', 0.4964606429195723)])), ('segm', OrderedDict([('AP', 0.35404836208584806), ('AP50', 0.558382551808117), ('AP75'
, 0.379614103783724), ('APs', 0.1613041010105462), ('APm', 0.37909971606652115), ('APl', 0.5174932965096802)]))])
```

Hi, I use the repo to train on train2017 and test on val2017, I does not change any other config, but the final AP (mask) is 35.4 which is lower 0.2 than 35.6, is it normal? Is this the normal performance variation?

**Comment by zjhuang22** [comment]
I have not run on coco2017 before. I have run several times on coco2014, the variation is 0.1. I‘m not sure whether there is any difference between coco2014 and coco2017. Maybe you should run maskrcnn on train2017 to see how the results are, and then compare whether the maskcoring rcnn's improvement is normal or not.

**Comment by yhcao6** [comment]
```
2019-05-03 02:39:19,210 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2019-05-03 02:39:19,210 maskrcnn_benchmark.inference INFO: Preparing bbox results
2019-05-03 02:39:20,843 maskrcnn_benchmark.inference INFO: Preparing segm results
5000it [04:23, 20.66it/s]
2019-05-03 02:43:44,124 maskrcnn_benchmark.inference INFO: Evaluating predictions
Loading and preparing results...
DONE (t=1.57s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=42.52s).
Accumulating evaluation results...
DONE (t=7.35s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.378
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.594
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.412
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.216
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.410
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.495
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.312
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.490
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.514
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.326
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.550
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.651
Loading and preparing results...
DONE (t=3.18s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=48.47s).
Accumulating evaluation results...
DONE (t=5.80s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.342
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.561
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.155
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.369
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.505
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.293
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.448
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.468
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.271
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.504
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.623
```

I have trained maskrcnn on train2017 and tested it on val2017, the performance is normal.

**Comment by zjhuang22** [comment]
My experiments show the variations of bbox AP and mask AP is both 0.1. Maybe the variation of 0.2 is normal. You can run a few more times to see whether the variation is normal.

**Comment by jpainam** [comment]
Hi, I trained the model on a custom dataset. The training worked perfectly, but running `python tools/test_net.py` to evaluate the model gives me this error
```python
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
2020-08-11 21:25:51,999 maskrcnn_benchmark.inference INFO: Start evaluation on 1042 images

Traceback (most recent call last):
  File "tools/test_net.py", line 94, in <module>
    main()
  File "tools/test_net.py", line 88, in main
    maskiou_on=cfg.MODEL.MASKIOU_ON
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/engine/inference.py", line 379, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/engine/inference.py", line 31, in compute_on_dataset
    output = model(images)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 43, in forward
    loss_maskiou, detections = self.maskiou(roi_feature, detections, selected_mask, labels, maskiou_targets)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py", line 41, in forward
    x = self.feature_extractor(features, selected_mask)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eldad/anaconda3/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py", line 39, in forward
    x = torch.cat((x, mask_pool), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 5 and 20 in dimension 0 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83
```
Is there something wrong with the `tools/test_net.py` file? I used `configs/e2e_ms_rcnn_R_50_FPN_1x.yaml`

**Comment by CaySue** [comment]
have you fixed it yet? i have the same problem with you.
