### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by ybxbupt** [zjhuang22/maskscoring_rcnn#50]
Traceback (most recent call last):
  File "/media/jiurui/92466C31466C186D/svn_all_20181126/yuanbaoxi/maskrcnntemp/maskscoring_rcnn-master/tools/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/media/jiurui/92466C31466C186D/svn_all_20181126/yuanbaoxi/maskrcnntemp/maskscoring_rcnn-master/maskrcnn_benchmark/engine/inference.py", line 20, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/media/jiurui/92466C31466C186D/svn_all_20181126/yuanbaoxi/maskrcnntemp/maskscoring_rcnn-master/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/media/jiurui/92466C31466C186D/svn_all_20181126/yuanbaoxi/maskrcnntemp/maskscoring_rcnn-master/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/media/jiurui/92466C31466C186D/svn_all_20181126/yuanbaoxi/maskrcnntemp/maskscoring_rcnn-master/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'

**Comment by zjhuang22** [comment]
Have you build the codes "make setup.py build develop"?

**Comment by SeavanMao** [comment]
I have the same problem. Have you solved this? @ybxbupt 
I did build this on windows and succeeded, but still have this error.

**Comment by guruL** [comment]
Hi! I have same problem.

> Have you build the codes "make setup.py build develop"?

Do you mean "python setup.py build develop"?

What's your python version and pytorch version?

**Comment by ybxbupt** [comment]
> Have you build the codes "make setup.py build develop"?

yes,I have run "python setup.py build develop", and success

$ python setup.py build develop
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'
running build
running build_py
running build_ext
running develop
running egg_info
writing maskrcnn_benchmark.egg-info/PKG-INFO
writing dependency_links to maskrcnn_benchmark.egg-info/dependency_links.txt
writing top-level names to maskrcnn_benchmark.egg-info/top_level.txt
reading manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
writing manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so -> maskrcnn_benchmark
Creating /home/jiurui/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/maskrcnn-benchmark.egg-link (link to .)
maskrcnn-benchmark 0.1 is already the active version in easy-install.pth

Installed /media/jiurui/C14D581BDA18EBFA/temp/maskscoring_rcnn-master
Processing dependencies for maskrcnn-benchmark==0.1
Finished processing dependencies for maskrcnn-benchmark==0.1

**Comment by ybxbupt** [comment]
change to gcc-5
then "python setup.py build develop" success

cd /usr/bin
sudo rm gcc
sudo rm g++
sudo ln -s /usr/bin/gcc-5 gcc
sudo ln -s /usr/bin/g++-5 g++

cd /usr/local/cuda-9.0/bin
sudo rm gcc
sudo rm g++
sudo ln -s /usr/bin/gcc-5 gcc
sudo ln -s /usr/bin/g++-5 g++

    Check if gcc and g++ version changed to 5.5.0 accordingly.

    Add -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 to setup.py file

    if torch.cuda.is_available() and CUDA_HOME is not None:
        extension = CUDAExtension
        sources += source_cuda
        define_macros += [("WITH_CUDA", None)]
        extra_compile_args["nvcc"] = [
            "-DCUDA_HAS_FP16=1",
            "-D__CUDA_NO_HALF_OPERATORS__",
            "-D__CUDA_NO_HALF_CONVERSIONS__",
            "-D__CUDA_NO_HALF2_OPERATORS__",
            "-DCUDA_HOST_COMPILER=/usr/bin/gcc-5"
        ]

    Do rm -rd build/

    Compile again with:

CUDAHOSTCXX=/usr/bin/gcc-5 python setup.py build develop

**Comment by yiming-lzx** [comment]
I had meet the same problem too. And I found that I run this project in a wrong environment. It not the compile environment. maybe you can check your environment.
I changed my environment and it worked.

**Comment by WangLanxiao** [comment]
i have meet the same question have you solved it now?
